plugins {
    id 'org.springframework.boot' version '2.2.4.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
    id 'java'
}

group = 'com.globant/BrainWaves/BWSegmenter'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
}

ext {
    set('springCloudVersion', "Hoxton.RC2")
    set('AkkaVersion', "2.6.1")
    set('AlpakkaVersion', "1.1.2")
    set('AlpakkaKafkaVersion', "1.1.0")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation "com.lightbend.akka:akka-stream-alpakka-elasticsearch_2.12:${AlpakkaVersion}"
    implementation "com.typesafe.akka:akka-stream-kafka_2.13:${AlpakkaKafkaVersion}"
    implementation "com.typesafe.akka:akka-stream_2.12:${AkkaVersion}"
    implementation "com.typesafe.akka:akka-actor-typed_2.13:${AkkaVersion}"
    implementation "com.typesafe.akka:akka-actor_2.13:${AkkaVersion}"
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

test {
    useJUnitPlatform()
}
